// globals definieren für überschrift in den Tabellen (entspricht den variable labels)
	global length_of_stay		"Average length of stay"
	global summ_stay			"Accumulated length of stay"
	global share_surgery		"Share with surgery"
	global hospital				"Hospital admission"
	global d1					"Certain infectious and parasitic diseases"
	global d2					"Neoplasms"
	global d5					"Mental and behavioral disorders"
	global d6 					"Diseases of the nervous system"
	global d7 					"Diseases of the eye and ear"
	global d8 					"Diseases of the circulatory system"
	global d9 					"Diseases of the respiratory system"
	global d10 					"Diseases of the digestive system"
	global d11 					"Diseases of the skin and subcutaneous tissue"
	global d12 					"Diseases of the musculoskeletal system and connective tissue"
	global d13 					"Diseases of the genitourinary system"
	global d17 					"Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified"
	global d18 					"External causes of morbidity and mortality"
	
	global metabolic_syndrome 	"Incidence of metabolic Syndrome"	
	global respiratory_index 	"Index respiratory system"
	global drug_abuse 			"Psychoactive substance abuse"
	global heart				"Non-ischemic heart diseases"
		
	global injuries 			"Injuries"
	global neurosis 			"Neurosis"
	global joints 				"Disease of the joints"
	global kidneys 				"Diseases of the kidneys"
	global bile_pancreas		"Diseases of the bile and pancreas"
		
	global d14 					"Pregnancy, childbirth and the puerperium"
	global female_genital_tract	"Non-inflammatory diseases of the female genital tract"
	global pregnancy			"Diseases of the mother, associated with the pregnancy"
	global delivery 			"Obstructed labor \& problems during delivery"
	
	global stomach				"Diseases of the stomach"
	global symp_dig_system		"Symptoms of the digestive system"
	global mal_neoplasm			"Malignant neoplasm"
	global ben_neoplasm			"Benign neoplasm"

	global depression			"Depression"
	global personality			"Personality and behavioral disorder"
	global lymphoma				"Diseases of the blood \& lymphatic vessels"
	global symp_resp_system		"Symptoms of the respiratory \& circulatory system"
	global calculi				"Renal insufficiency (Calculi)"
********************************************************************************

// global for variable name (include \ with underscores): necessary to include variable name in notes of tables

	global varname_length_of_stay		"length$\_$of$\_$stay"                               
	global varname_summ_stay			"summ$\_$stay"                           
	global varname_share_surgery		"share$\_$surgery"                           
	global varname_hospital				"hospital"                           
	global varname_d1					"d1"                               
	global varname_d2					"d2"                               
	global varname_d5					"d5"                               
	global varname_d6 					"d6"                               
	global varname_d7 					"d7"                               
	global varname_d8 					"d8"                               
	global varname_d9 					"d9"                               
	global varname_d10 					"d10"                           
	global varname_d11 					"d11"                           
	global varname_d12 					"d12"                           
	global varname_d13 					"d13"                           
	global varname_d17 					"d17"                           
	global varname_d18 					"d18"                           
	
	global varname_metabolic_syndrome 	"metabolic$\_$syndrome"                            
	global varname_respiratory_index 	"respiratory$\_$index"                             
	global varname_drug_abuse 			"drug$\_$abuse"                               
	global varname_heart				"heart"                           
		
	global varname_injuries 			"injuries"                           
	global varname_neurosis 			"neurosis"                           
	global varname_joints 				"joints"                               
	global varname_kidneys 				"kidneys"                           
	global varname_bile_pancreas		"bile$\_$pancreas"                           
		
	global varname_d14 					"d14"                           
	global varname_female_genital_tract	"female$\_$genital$\_$tract"                           
	global varname_pregnancy			"pregnancy"                           
	global varname_delivery 			"delivery"                           
	
	global varname_stomach				"stomach"                               
	global varname_symp_dig_system		"symp$\_$dig$\_$system"                               
	global varname_mal_neoplasm			"mal$\_$neoplasm"                           
	global varname_ben_neoplasm			"ben$\_$neoplasm"                           

	global varname_depression			"depression"                               
	global varname_personality			"personality"                               
	global varname_lymphoma				"lymphoma"                           
	global varname_symp_resp_system		"symp$\_$resp$\_$system"                           
	global varname_calculi				"calculi"                               
	
	